name: Release drafter

on:
  push:
    branches: '2pr'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: get_data
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
          echo "${{ github.ref_name }} Commit: ${{ github.sha }}"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_data.outputs.approvers }}
          minimum-approvals: 1
          issue-title: 'Release opensearch-dsl-py'
          issue-body: "Please approve or deny the release of opensearch-dsl-py. Tag:${{env.GITHUB_REF_NAME}} Commit: ${{env.GITHUB_SHA}}"
          # exclude-workflow-initiator-as-approver: true
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install build tools
        run: |
          python -m pip install --upgrade build
      - name: Build project for distribution
        run: |
          python -m build
          tar -zvcf artifacts.tar.gz dist
      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            artifacts.tar.gz
